spring.profiles.active: 'test'

# Spring
spring:
  # Datasource
  datasource:
    url: "jdbc:h2:mem:db;DB_CLOSE_DELAY=-1"
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

    # Connection pool
    hikari:
      connection-timeout: 20000
      maximum-pool-size:  5

  # JPA
  jpa:
    database: h2
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

# Logging
logging:
  pattern.console: "%-5level %logger{36} - %msg%n"
#  level:
#    org.springframework: INFO
#    com.zaxxer: ERROR
#    root: ERROR